services:
  frontend:
    build:
      context: ./front_end_app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build:
      context: ./back_end_app
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: admin
      DB_NAME: luc_products
      PORT: 3000
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: luc_products
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
